// <auto-generated />
namespace HaberSistemi.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Olustur : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Olustur));
        
        string IMigrationMetadata.Id
        {
            get { return "201801181210456_Olustur"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
